//! TypeScript Exporter Script — PRODUCTION-GRADE ARCHITECTURE
//!
//! This script extracts type definitions from the Rust kernel and generates
//! highly-type-safe TypeScript interfaces and enums for frontend synchronization.

use std::fs::File;
use std::io::{Write, Read};

fn main() -> std::io::Result<()> {
    println!("Starting structured TypeScript generation...");

    let mut output = String::new();

    // Header with timestamp tracking
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    output.push_str("// Auto-generated by generate_ts.rs. DO NOT EDIT.\n");
    output.push_str("// This file is synchronized with the Rust v8_types_kernel.\n");
    output.push_str(&format!("// Generated at Unix timestamp: {}\n\n", now));

    generate_all_sections(&mut output)?;

    // Final file generation
    let mut file = File::create("v8_kernel_types.ts")?;
    file.write_all(output.as_bytes())?;

    println!("✅ Generated: v8_kernel_types.ts (Comprehensive Structured Version)");

    Ok(())
}

fn generate_all_sections(output: &mut String) -> std::io::Result<()> {
    // Section 1: Branded Types
    generate_branded_types(output);

    // Section 2-3: Heap & Memory (MMU Simulation)
    generate_heap_types(output)?;

    // Section 4-15: JS Objects
    generate_object_types(output)?;

    // Section 43-44: Compiler Pipeline (Speculative JIT)
    generate_compiler_types(output)?;

    // Section 45: Sandbox
    generate_sandbox_types(output)?;

    // Section 51: DFFDF
    generate_dffdf_types(output)?;

    // Section 53: Kernel Scheduler (AMB)
    generate_amb_types(output)?;

    // Section 29-33: Advanced Speculative Research
    generate_advanced_types(output)?;

    // Section 101+: Topos Integration
    generate_topos_types(output)?;

    Ok(())
}

fn generate_branded_types(output: &mut String) {
    output.push_str("/** Section 1: Branded Types */\n");
    output.push_str("export type ObjectIndex = number & { readonly __brand: 'ObjectIndex' };\n");
    output.push_str("export type MapIndex = number & { readonly __brand: 'MapIndex' };\n");
    output.push_str("export type TaggedAddress = bigint & { readonly __brand: 'TaggedAddress' };\n\n");
}

fn generate_heap_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 2-3: Heap & Memory MMU */\n");
    scan_and_export_enum(output, "src/heap/mod.rs", "InstanceType")?;
    scan_and_export_struct(output, "src/heap/mod.rs", "HeapStats")?;
    Ok(())
}

fn generate_object_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 4-15: JS Objects */\n");
    scan_and_export_enum(output, "src/objects/mod.rs", "PromiseState")?;
    Ok(())
}

fn generate_compiler_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 43-44: Compiler Pipeline */\n");
    scan_and_export_enum(output, "src/compiler/mod.rs", "ExecutionTier")?;
    scan_and_export_enum(output, "src/compiler/mod.rs", "ICState")?;
    Ok(())
}

fn generate_sandbox_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 45: Sandbox */\n");
    scan_and_export_struct(output, "src/sandbox/mod.rs", "V8Sandbox")?;
    Ok(())
}

fn generate_dffdf_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 51: DFFDF */\n");
    output.push_str("export interface FailureContext {\n");
    output.push_str("  readonly kind: string;\n");
    output.push_str("  readonly severity: string;\n");
    output.push_str("  readonly timestamp: number;\n");
    output.push_str("  readonly message: string;\n");
    output.push_str("}\n");
    scan_and_export_struct(output, "src/dffdf/mod.rs", "DiagnosticReport")?;
    Ok(())
}

fn generate_amb_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 53: Kernel Scheduler */\n");
    scan_and_export_enum(output, "src/amb/mod.rs", "TaskState")?;
    scan_and_export_struct(output, "src/amb/mod.rs", "KernelTask")?;
    Ok(())
}

fn generate_advanced_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 29-33: Speculative Research */\n");
    scan_and_export_struct(output, "src/advanced/mod.rs", "TopologicalSpace")?;
    scan_and_export_struct(output, "src/advanced/mod.rs", "QuantumState")?;
    Ok(())
}

fn generate_topos_types(output: &mut String) -> std::io::Result<()> {
    output.push_str("/** Section 101+: Topos Integration */\n");
    scan_and_export_enum(output, "src/topos/mod.rs", "PageTableLevel")?;
    scan_and_export_enum(output, "src/topos/mod.rs", "KripkeStage")?;
    scan_and_export_enum(output, "src/topos/mod.rs", "ModalOperator")?;
    scan_and_export_enum(output, "src/topos/mod.rs", "TruthValue")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "MemoryShape")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "HomotopyResult")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "ErrorFactorization")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "SystemContext")?;

    output.push_str("/** HoTT Abstractions */\n");
    scan_and_export_struct(output, "src/topos/mod.rs", "PathP")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "Homotopy2")?;
    scan_and_export_struct(output, "src/topos/mod.rs", "KanComplex")?;
    Ok(())
}

/// A simple scanner that finds an enum definition in a Rust file and exports it to TS.
fn scan_and_export_enum(output: &mut String, path: &str, enum_name: &str) -> std::io::Result<()> {
    let mut content = String::new();
    if let Ok(mut file) = File::open(path) {
        file.read_to_string(&mut content)?;

        if let Some(start) = content.find(&format!("pub enum {} {{", enum_name)) {
            let rest = &content[start..];
            if let Some(end) = rest.find('}') {
                let body = &rest[..end + 1];

                output.push_str(&format!("export enum {} {{\n", enum_name));

                let mut value_counter = 0;
                for line in body.lines() {
                    let trimmed = line.trim();
                    if trimmed.is_empty() || trimmed.starts_with("pub enum") || trimmed.starts_with('}') || trimmed.starts_with('/') || trimmed.starts_with('#') {
                        continue;
                    }

                    let variant_full = trimmed.split(',').next().unwrap_or("").split('=').next().unwrap_or("").trim();
                    if !variant_full.is_empty() {
                        // Strip data fields like { ... } or ( ... )
                        let variant = variant_full.split('{').next().unwrap_or("").split('(').next().unwrap_or("").trim();
                        if !variant.is_empty() {
                            output.push_str(&format!("  {} = {},\n", variant, value_counter));
                            value_counter += 1;
                        }
                    }
                }
                output.push_str("}\n\n");
            }
        }
    }
    Ok(())
}

/// A scanner that finds a struct definition and exports it as a TS interface.
fn scan_and_export_struct(output: &mut String, path: &str, struct_name: &str) -> std::io::Result<()> {
    let mut content = String::new();
    if let Ok(mut file) = File::open(path) {
        file.read_to_string(&mut content)?;

        if let Some(start) = content.find(&format!("pub struct {}", struct_name)) {
            let rest = &content[start..];
            if let Some(end) = rest.find('}') {
                let body = &rest[..end + 1];

                output.push_str(&format!("export interface {} {{\n", struct_name));

                for line in body.lines() {
                    let trimmed = line.trim();
                    if !trimmed.starts_with("pub ") || trimmed.contains("struct ") || trimmed.contains('}') {
                        continue;
                    }

                    let parts: Vec<&str> = trimmed.split(':').collect();
                    if parts.len() == 2 {
                        let field = parts[0].trim_start_matches("pub ").trim();
                        let rust_type = parts[1].trim_end_matches(',').trim();

                        if field == "failures" && rust_type == "Vec<FailureKind>" {
                            output.push_str("  readonly failures: ReadonlyArray<FailureContext>;\n");
                            continue;
                        }

                        let ts_type = match rust_type {
                            "usize" | "u32" | "u64" | "i32" | "f64" | "u8" | "i8" | "f32" => "number",
                            "String" | "&'static str" => "string",
                            "bool" | "boolean" => "boolean",
                            "BrandedVAddr" | "TaggedAddress" => "TaggedAddress",
                            "BrandedTaskId" => "number",
                            "BrandedPAddr" => "number",
                            "PageRange" => "any",
                            "[f32; 4]" => "ReadonlyArray<number>",
                            "Vec<TracePoint>" => "ReadonlyArray<any>",
                            "Vec<FailureKind>" | "ReadonlyArray<FailureContext>" => "ReadonlyArray<FailureContext>",
                            "Vec<BrandedTaskId>" => "ReadonlyArray<number>",
                            "HashMap<String, u64>" => "{ [key: string]: number }",
                            _ => if rust_type.starts_with("Vec<") { "ReadonlyArray<any>" } else { "any" },
                        };
                        output.push_str(&format!("  readonly {}: {};\n", field, ts_type));
                    }
                }
                output.push_str("}\n\n");
            }
        }
    }
    Ok(())
}
