//! TypeScript Exporter Script.
//!
//! This script simulates a scanner that extracts Rust type definitions
//! and generates matching TypeScript interfaces and enums.
//! This ensures the frontend stays in sync with the kernel's data-oriented structures.
//!
//! # Rationale
//! In a complex system like a V8 simulation, keeping the frontend and backend
//! types in sync manually is error-prone. This script automates that process
//! by reading the Rust source code and generating a `.ts` file.
//!
//! # Implementation Details
//! The script uses a simple line-by-line scanner to find `pub enum` and
//! `pub struct` definitions. It handles basic variant extraction and field
//! mapping to TypeScript types.
//!
//! # Usage
//! Run this script via Cargo:
//! ```bash
//! cargo run --bin generate_ts
//! ```

use std::fs::File;
use std::io::{Write, Read};
use std::path::Path;

fn main() -> std::io::Result<()> {
    println!("Starting production-grade TypeScript generation...");

    let mut output = File::create("v8_kernel_types.ts")?;
    writeln!(output, "// Auto-generated by generate_ts.rs. DO NOT EDIT.")?;
    writeln!(output, "// Generated at: {}", std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs())?;
    writeln!(output)?;

    // Export Core Newtypes
    writeln!(output, "/** Unique identifier for a HeapObject */")?;
    writeln!(output, "export type ObjectIndex = number;")?;
    writeln!(output, "/** Unique identifier for a Map (Hidden Class) */")?;
    writeln!(output, "export type MapIndex = number;")?;
    writeln!(output, "/** Tagged 64-bit word (Smi or Pointer) */")?;
    writeln!(output, "export type TaggedAddress = bigint;")?;
    writeln!(output)?;

    // Extract and export Enums from Rust source files
    scan_and_export_enum(&mut output, "src/heap/mod.rs", "InstanceType")?;
    scan_and_export_enum(&mut output, "src/objects/mod.rs", "PromiseState")?;
    scan_and_export_enum(&mut output, "src/compiler/mod.rs", "ExecutionTier")?;
    scan_and_export_enum(&mut output, "src/compiler/mod.rs", "ICState")?;
    scan_and_export_enum(&mut output, "src/streaming/mod.rs", "StreamingState")?;

    // Extract and export Structs as Interfaces
    scan_and_export_struct(&mut output, "src/heap/mod.rs", "HeapStats")?;
    scan_and_export_struct(&mut output, "src/dffdf/mod.rs", "DiagnosticReport")?;

    println!("TypeScript types generated successfully to v8_kernel_types.ts");
    Ok(())
}

/// A scanner that finds an enum definition and exports it to TS.
fn scan_and_export_enum(output: &mut File, path: &str, enum_name: &str) -> std::io::Result<()> {
    let mut content = String::new();
    let mut file = File::open(Path::new(path))?;
    file.read_to_string(&mut content)?;

    if let Some(start) = content.find(&format!("pub enum {} {{", enum_name)) {
        let rest = &content[start..];
        if let Some(end) = rest.find('}') {
            let body = &rest[..end + 1];

            writeln!(output, "/** Source: {} */", path)?;
            writeln!(output, "export enum {} {{", enum_name)?;

            let mut value_counter = 0;
            for line in body.lines() {
                let trimmed = line.trim();
                if trimmed.is_empty() || trimmed.starts_with("pub enum") || trimmed.starts_with('}') || trimmed.starts_with('/') || trimmed.starts_with('#') {
                    continue;
                }

                let variant = trimmed.split(',').next().unwrap_or("").split('=').next().unwrap_or("").trim();
                if !variant.is_empty() {
                    writeln!(output, "  {} = {},", variant, value_counter)?;
                    value_counter += 1;
                }
            }
            writeln!(output, "}}")?;
            writeln!(output)?;
        }
    }

    Ok(())
}

/// A scanner that finds a struct definition and exports it as a TS interface.
fn scan_and_export_struct(output: &mut File, path: &str, struct_name: &str) -> std::io::Result<()> {
    let mut content = String::new();
    let mut file = File::open(Path::new(path))?;
    file.read_to_string(&mut content)?;

    if let Some(start) = content.find(&format!("pub struct {} {{", struct_name)) {
        let rest = &content[start..];
        if let Some(end) = rest.find('}') {
            let body = &rest[..end + 1];

            writeln!(output, "/** Source: {} */", path)?;
            writeln!(output, "export interface {} {{", struct_name)?;

            for line in body.lines() {
                let trimmed = line.trim();
                if !trimmed.starts_with("pub ") || trimmed.contains("struct ") || trimmed.contains('}') {
                    continue;
                }

                // Simple parser for "pub field: type,"
                let parts: Vec<&str> = trimmed.split(':').collect();
                if parts.len() == 2 {
                    let field = parts[0].trim_start_matches("pub ").trim();
                    let rust_type = parts[1].trim_end_matches(',').trim();
                    let ts_type = match rust_type {
                        "usize" | "u32" | "u64" | "i32" | "f64" => "number",
                        "String" | "&'static str" => "string",
                        "bool" => "boolean",
                        _ => "any",
                    };
                    writeln!(output, "  {}: {};", field, ts_type)?;
                }
            }
            writeln!(output, "}}")?;
            writeln!(output)?;
        }
    }

    Ok(())
}
