// Auto-generated by generate_ts.rs. DO NOT EDIT.
// This file is synchronized with the Rust v8_types_kernel.
// Generated at Unix timestamp: 1782069853

/** Branded type for object indices in the SoA heap */
export type ObjectIndex = number & { readonly __brand: 'ObjectIndex' };

/** Branded type for map (hidden class) indices */
export type MapIndex = number & { readonly __brand: 'MapIndex' };

/** Branded type for tagged 64-bit words (Smi or Pointer) */
export type TaggedAddress = bigint & { readonly __brand: 'TaggedAddress' };

/** Source: src/heap/mod.rs */
export enum InstanceType {
  JSObject = 0,
  JSArray = 1,
  JSPromise = 2,
  String = 3,
  Map = 4,
  InternalizedString = 5,
  SharedFunctionInfo = 6,
  FeedbackVector = 7,
  Oddball = 8,
  FixedArray = 9,
  ByteArray = 10,
}

/** Source: src/objects/mod.rs */
export enum PromiseState {
  Pending = 0,
  Fulfilled = 1,
  Rejected = 2,
}

/** Source: src/compiler/mod.rs */
export enum ExecutionTier {
  Ignition = 0,
  Sparkplug = 1,
  Maglev = 2,
  Turbofan = 3,
}

/** Source: src/compiler/mod.rs */
export enum ICState {
  Uninitialized = 0,
  PreMonomorphic = 1,
  Monomorphic = 2,
  Polymorphic = 3,
  Megamorphic = 4,
  Generic = 5,
}

/** Source: src/streaming/mod.rs */
export enum StreamingState {
  Initial = 0,
  HeaderParsing = 1,
  BodyParsing = 2,
  Finalizing = 3,
  Error = 4,
}

/** Source: src/heap/mod.rs */
export interface HeapStats {
  readonly object_count: number;
  readonly property_count: number;
  readonly element_count: number;
  readonly memory_usage_bytes: number;
  readonly peak_memory_bytes: number;
  readonly gc_cycles: number;
}

/** Detailed context for a kernel-level failure */
export interface FailureContext {
  readonly kind: FailureKind;
  readonly severity: FailureSeverity;
  readonly timestamp: number;
  readonly message: string;
}

/** Aggregated diagnostic report from the DFFDF */
export interface DiagnosticReport {
  readonly failures: ReadonlyArray<FailureContext>;
  readonly timestamp: number;
  readonly session_id: string;
}

/** Domain-specific failure categories */
export type FailureKind =
  | 'kOutOfBoundsAccess'
  | 'kHeapCorruption'
  | 'kDeoptimization'
  | 'kCompilationError'
  | 'kOutOfMemory'
  | 'kSecurityViolation';

/** Severity levels for diagnostic alerts */
export type FailureSeverity =
  | 'kFatal'
  | 'kCritical'
  | 'kError'
  | 'kWarning'
  | 'kInfo';
