// Auto-generated by generate_ts.rs. DO NOT EDIT.
// Generated at: 1782058323

/** Unique identifier for a HeapObject */
export type ObjectIndex = number;
/** Unique identifier for a Map (Hidden Class) */
export type MapIndex = number;
/** Tagged 64-bit word (Smi or Pointer) */
export type TaggedAddress = bigint;

/** Original Rust definition found in src/heap/mod.rs */
export enum InstanceType {
  JSObject = 0,
  JSArray = 1,
  JSPromise = 2,
  String = 3,
  Map = 4,
  InternalizedString = 5,
  SharedFunctionInfo = 6,
  FeedbackVector = 7,
  Oddball = 8,
  FixedArray = 9,
  ByteArray = 10,
}

/** Original Rust definition found in src/objects/mod.rs */
export enum PromiseState {
  Pending = 0,
  Fulfilled = 1,
  Rejected = 2,
}

/** Original Rust definition found in src/compiler/mod.rs */
export enum ExecutionTier {
  Ignition = 0,
  Sparkplug = 1,
  Maglev = 2,
  Turbofan = 3,
}

/** Original Rust definition found in src/compiler/mod.rs */
export enum ICState {
  Uninitialized = 0,
  PreMonomorphic = 1,
  Monomorphic = 2,
  Polymorphic = 3,
  Megamorphic = 4,
  Generic = 5,
}

/** Structure of Arrays (SoA) layout for the V8 Heap */
export interface HeapStats {
  object_count: number;
  property_count: number;
  element_count: number;
  memory_usage_bytes: number;
}
