// Auto-generated by generate_ts.rs. DO NOT EDIT.

/** Branded Types */
export type ObjectIndex = number & { readonly __brand: 'ObjectIndex' };
export type MapIndex = number & { readonly __brand: 'MapIndex' };
export type TaggedAddress = bigint & { readonly __brand: 'TaggedAddress' };

export enum InstanceType {
  JSObject = 0,
  JSArray = 1,
  JSPromise = 2,
  String = 3,
  Map = 4,
  InternalizedString = 5,
  SharedFunctionInfo = 6,
  FeedbackVector = 7,
  Oddball = 8,
  FixedArray = 9,
  ByteArray = 10,
}

export interface MemorySegment {
  readonly start_address: number;
  readonly size: number;
  readonly used_bytes: number;
  readonly protection: unknown;
}

export interface ProtectionFlags {
  readonly readable: boolean;
  readonly writable: boolean;
  readonly executable: boolean;
}

export interface Heap {
  readonly instance_types: ReadonlyArray<unknown>;
  readonly map_indices: ReadonlyArray<unknown>;
  readonly tagged_addresses: ReadonlyArray<unknown>;
  readonly ages: ReadonlyArray<unknown>;
  readonly marking_state: ReadonlyArray<unknown>;
  readonly properties_offsets: ReadonlyArray<unknown>;
  readonly properties_lengths: ReadonlyArray<unknown>;
  readonly properties_data: ReadonlyArray<unknown>;
  readonly elements_offsets: ReadonlyArray<unknown>;
  readonly elements_lengths: ReadonlyArray<unknown>;
  readonly elements_data: ReadonlyArray<unknown>;
  readonly segments: ReadonlyArray<unknown>;
  readonly max_objects: number;
  readonly allocated_bytes: number;
  readonly gc_count: number;
  readonly peak_memory: number;
}

export interface PageTable {
  readonly l4_table: ReadonlyArray<unknown>;
  readonly l3_tables: ReadonlyArray<unknown>;
  readonly l2_tables: ReadonlyArray<unknown>;
  readonly l1_tables: ReadonlyArray<unknown>;
  readonly total_mappings: number;
}

export interface HeapStats {
  readonly object_count: number;
  readonly property_count: number;
  readonly element_count: number;
  readonly memory_usage_bytes: number;
  readonly peak_memory_bytes: number;
  readonly gc_cycles: number;
}

export interface MarkingBitmap {
  readonly data: ReadonlyArray<unknown>;
  readonly size_bits: number;
}

export enum PromiseState {
  Pending = 0,
  Fulfilled = 1,
  Rejected = 2,
}

export enum ReactionType {
  Fulfill = 0,
  Reject = 1,
}

export enum ExternalArrayType {
  Int8 = 0,
  Uint8 = 1,
  Uint8Clamped = 2,
  Int16 = 3,
  Uint16 = 4,
  Int32 = 5,
  Uint32 = 6,
  Float32 = 7,
  Float64 = 8,
  BigInt64 = 9,
  BigUint64 = 10,
}

export enum ObjectMode {
  Fast = 0,
  Dictionary = 1,
}

export interface JSObject {
  readonly index: number;
}

export interface JSPromise {
  readonly index: number;
}

export interface JSArray {
  readonly index: number;
}

export interface JSString {
  readonly index: number;
}

export interface SharedFunctionInfo {
  readonly index: number;
}

export interface FeedbackVector {
  readonly index: number;
}

export interface JSFunction {
  readonly index: number;
}

export interface AccessorInfo {
  readonly index: number;
}

export interface JSProxy {
  readonly index: number;
}

export interface JSMap {
  readonly index: number;
}

export interface JSSet {
  readonly index: number;
}

export interface JSContext {
  readonly index: number;
}

export interface JSGlobalProxy {
  readonly index: number;
}

export interface JSTypedArray {
  readonly index: number;
}

export interface JSDataView {
  readonly index: number;
}

export interface JSDate {
  readonly index: number;
}

export interface JSRegExp {
  readonly index: number;
}

export interface JSAsyncFunction {
  readonly index: number;
}

export interface JSGeneratorObject {
  readonly index: number;
}

export interface JSIteratorResult {
  readonly index: number;
}

export interface MapTransition {
  readonly from: number;
  readonly to: number;
  readonly property_name: bigint;
}

export interface TransitionTree {
  readonly transitions: ReadonlyArray<unknown>;
}

export interface DoubleField {
  readonly value: number;
}

export interface JSReceiver {
  readonly index: number;
}

export interface JSBoundFunction {
  readonly index: number;
}

export interface JSMessageObject {
  readonly index: number;
}

export interface BytecodeArray {
  readonly index: number;
}

export interface ScopeInfo {
  readonly index: number;
}

export interface ConstantPool {
  readonly index: number;
}

export enum ExecutionTier {
  Ignition = 0,
  Sparkplug = 1,
  Maglev = 2,
  Turbofan = 3,
  ExperimentalSpeculative = 4,
}

export enum ICState {
  Uninitialized = 0,
  PreMonomorphic = 1,
  Monomorphic = 2,
  Polymorphic = 3,
  Megamorphic = 4,
  Generic = 5,
}

export enum DeoptReason {
  WrongInstanceType = 0,
  OutOfMemory = 1,
  MissingProperty = 2,
  ArrayBoundsCheckFailed = 3,
}

export interface InlineCache {
  readonly state: unknown;
  readonly hits: number;
  readonly misses: number;
  readonly call_count: number;
}

export interface SpeculativeJIT {
  readonly predictor: unknown;
  readonly optimizations_performed: number;
}

export interface OptimizationPass {
  readonly name: string;
  readonly is_enabled: boolean;
}

export interface Deoptimizer {
  readonly reason: unknown;
  readonly bailout_id: number;
}

export interface RegisterAllocator {
  readonly available_registers: number;
}

export interface CodeCache {
  readonly version: number;
  readonly payload: ReadonlyArray<unknown>;
}

export enum FailureKind {
  OutOfBounds = 0,
  InvalidTag = 1,
  HeapExhausted = 2,
  InvalidStateTransition = 3,
  BatchFailure = 4,
  CircuitBreakerTripped = 5,
  SecurityViolation = 6,
  SystemError = 7,
  WasmValidationError = 8,
  GCError = 9,
  SheafGluingContradiction = 10,
  InvalidDelegation = 11,
  ModalContradiction = 12,
  HomotopyStuckLoop = 13,
  PathContradiction = 14,
  UnivalenceViolation = 15,
}

export interface CircuitBreaker {
}

export interface DiagnosticReport {
  readonly failures: ReadonlyArray<unknown>;
  readonly timestamp: number;
  readonly session_id: string;
}

export interface ErrorLog {
  readonly entries: ReadonlyArray<unknown>;
}

export enum GCReason {
  AllocationFailure = 0,
  ManualTrigger = 1,
  MemoryPressure = 2,
  ExternalRequest = 3,
}

export enum GCKind {
  Scavenge = 0,
  MarkSweepCompact = 1,
  IncrementalMarkingStep = 2,
}

export enum MarkingColor {
  White = 0,
  Grey = 1,
  Black = 2,
}

export enum IncrementalMarkingState {
  Stopped = 0,
  Marking = 1,
  Completing = 2,
}

export interface GCResult {
  readonly bytes_freed: number;
  readonly duration_ms: number;
  readonly survived_objects: number;
  readonly kind: unknown;
}

export interface NewSpace {
  readonly from_space_base: number;
  readonly to_space_base: number;
  readonly capacity: number;
  readonly top: number;
}

export interface OldSpace {
  readonly base: number;
  readonly capacity: number;
  readonly free_list: ReadonlyArray<unknown>;
}

export interface OrinocoGC {
  readonly young_gen: unknown;
  readonly old_gen: unknown;
  readonly marking_state: unknown;
  readonly worklist: ReadonlyArray<unknown>;
}

export enum PageTableLevel {
  L1 = 0,
  L2 = 1,
  L3 = 2,
  L4 = 3,
}

export enum KripkeStage {
  Idle = 0,
  Running = 1,
  Terminated = 2,
}

export enum ModalOperator {
  Necessity = 0,
  Possibility = 1,
  Eventually = 2,
  Henceforth = 3,
}

export interface SheafSection {
  readonly domain: unknown;
  readonly data: ReadonlyArray<unknown>;
  readonly version: number;
}

export interface PageRange {
  readonly start: bigint;
  readonly end: bigint;
  readonly level: unknown;
}

export interface CechCohomology {
  readonly degree: number;
  readonly cocycle: boolean;
  readonly obstruction: unknown;
}

export interface PageOverlap {
  readonly levels: ReadonlyArray<unknown>;
  readonly virtual_range: unknown;
  readonly physical_mappings: ReadonlyArray<unknown>;
}

export interface MmuSheaf {
  readonly sections: { [key: string]: unknown };
}

export interface SchedulerTopos {
  readonly stages: ReadonlyArray<unknown>;
  readonly current_stage: number;
}

export interface MemoryNode {
  readonly id: bigint;
}

export interface MemoryCohesion {
  readonly nodes: ReadonlyArray<unknown>;
}

export interface MemoryShape {
  readonly connected_components: number;
  readonly euler_characteristic: number;
  readonly cache_efficiency: string;
}

export interface TracePoint {
  readonly action: string;
  readonly operand: bigint;
  readonly state_hash: number;
}

export interface ExecutionHomotopy {
  readonly paths: ReadonlyArray<unknown>;
}

export interface MemoryAccess {
  readonly address: bigint;
  readonly size: number;
}

export interface ErrorFactorization {
  readonly epi: string;
  readonly mono: { [key: string]: unknown };
}

export interface SystemContext {
  readonly valid_state: { [key: string]: unknown };
}

export interface ObjectTwoTopos {
  readonly hierarchy: { [key: string]: unknown };
}

export interface PathP {
  readonly start: unknown;
  readonly end: unknown;
  readonly mapping: string;
}

export interface Fibration {
  readonly projection: unknown;
}
